
title: "Sacrée sexualité"
description: "Sacrée sexualité — Sexualité & qualité de vie"
keywords: "sexualité, thérapies brèves, qualité de vie, Lausanne, Vallée de Joux, Suisse"
author: "Lætitia Stucki, Nicolas Jeanmonod"

locale: fr



url: "http://sacree-sexualite.org"
baseurl: "/"



markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

exclude: [ "CNAME", "README.md", "Gemfile", "Gemfile.lock" ]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

sass:
  sass_dir: assets/css
  style: compressed

gems:
  - jekyll-sitemap

